### ISSUE TITLE
README updates

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/SimulationService.jl#7]
We should at minimum provide a quickstart (e.g. `docker-compose up -d` once https://github.com/anandijain/SimulationService.jl/issues/4 is complete) and a couple example payloads.

**Comment by anandijain** [comment]
I haven't really used docker so I'll want some help on that, hopefully my adding those dockerfiles was enough to make that work. 

Also for something that will probably break and change so much, I'd prefer to not maintain a readme, and just have people read the `test/runtests.jl` file, which by nature of CI will stay up to date. In my upcoming commits, I'll have cleaned this up to be readable to people other than me.

**Comment by brandomr** [comment]
@anandijain my concern with that is we'd have to run Julia to even produce the example JSON payloads and not everyone will want to do that. Could you have `runtests.jl` write out the payloads as JSON and store them in some directory (e.g. `example_payloads`?
